# Generated by Django 4.2 on 2024-01-10 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_variant_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variant',
            old_name='product_attribute',
            new_name='attribute',
        ),
        migrations.RenameField(
            model_name='variant',
            old_name='product_attribute_value',
            new_name='attribute_value',
        ),
    ]
