# Generated by Django 4.2 on 2024-01-10 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_size_product_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='attribute_value',
        ),
        migrations.AddField(
            model_name='variant',
            name='size',
            field=models.ForeignKey(default='41', on_delete=django.db.models.deletion.PROTECT, related_name='variant_size', to='store.size'),
        ),
    ]
