# Generated by Django 4.2 on 2024-01-10 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_attribute_fa_name_alter_product_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='fa_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='attribute',
            unique_together={('fa_name', 'category')},
        ),
    ]
