# Generated by Django 4.2 on 2024-01-10 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_size_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='location',
        ),
    ]
