# Generated by Django 4.2 on 2024-01-18 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_productcomment_body_alter_productcomment_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcomment',
            old_name='name',
            new_name='user',
        ),
    ]
