# Generated by Django 4.2 on 2024-01-20 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_rename_name_productcomment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='size',
            old_name='size',
            new_name='title',
        ),
    ]
