# Generated by Django 4.2 on 2024-01-20 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_rename_size_size_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attributevalue',
            old_name='product_attribute',
            new_name='attribute',
        ),
    ]
