# Generated by Django 4.2 on 2024-01-21 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0021_rename_product_attribute_attributevalue_attribute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.ManyToManyField(blank=True, related_name='products', to='store.color', verbose_name='Product Colors'),
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(blank=True, to='store.size', verbose_name='Product Sizes'),
        ),
        migrations.AlterField(
            model_name='attributevalue',
            name='value',
            field=models.TextField(verbose_name='Values of Attribute'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='brand description'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='en_name',
            field=models.CharField(max_length=100, verbose_name='brand'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='fa_name',
            field=models.CharField(max_length=100, verbose_name='brand'),
        ),
        migrations.AlterField(
            model_name='category',
            name='en_name',
            field=models.CharField(max_length=100, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='fa_name',
            field=models.CharField(max_length=100, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='color',
            name='en_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='color'),
        ),
        migrations.AlterField(
            model_name='color',
            name='fa_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='color'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='covers/product_image/', verbose_name='Product Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='attribute',
            field=models.ManyToManyField(to='store.attribute', verbose_name='Product Attribute'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='store.brand', verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='store.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='en_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='English Product Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fa_name',
            field=models.CharField(max_length=255, verbose_name='Farsi Product Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='full_description',
            field=models.TextField(verbose_name='Product Full Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, verbose_name='Product Gender'),
        ),
        migrations.AlterField(
            model_name='product',
            name='model',
            field=models.CharField(blank=True, max_length=255, verbose_name='Product Model'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.CharField(max_length=5000, verbose_name='Product Short Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(to='store.tag', verbose_name='Product Tags'),
        ),
        migrations.AlterField(
            model_name='productcomment',
            name='body',
            field=models.TextField(verbose_name='Comment Text'),
        ),
        migrations.AlterField(
            model_name='productcomment',
            name='product_stars',
            field=models.CharField(choices=[('1', 'Very Bad'), ('2', 'Bad'), ('3', 'normal'), ('4', 'Good'), ('5', 'Perfect')], max_length=1, verbose_name='Rate of Product'),
        ),
        migrations.AlterField(
            model_name='productcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author Comment'),
        ),
        migrations.AlterField(
            model_name='productpricing',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.color', verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='productpricing',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price', to='store.product', verbose_name='Product Price'),
        ),
        migrations.AlterField(
            model_name='size',
            name='title',
            field=models.CharField(blank=True, max_length=50, verbose_name='size'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=255, verbose_name='tags'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='color_variant', to='store.color', verbose_name='Color Variant'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='inventory',
            field=models.PositiveIntegerField(default=0, verbose_name='Variant Inventory'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variant', to='store.product', verbose_name='Product Variant'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='size',
            field=models.ForeignKey(default='41', on_delete=django.db.models.deletion.PROTECT, related_name='variant_size', to='store.size', verbose_name='Size Variant'),
        ),
    ]
