# Generated by Django 4.2 on 2024-02-03 05:24

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_alter_product_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='full_description',
            field=ckeditor.fields.RichTextField(verbose_name='Product Full Description'),
        ),
    ]
