# Generated by Django 4.2 on 2024-02-04 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_note',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
