# Generated by Django 4.2 on 2024-02-04 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_order_order_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='post_code',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
