# Generated by Django 4.2 on 2024-02-04 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_alter_order_address_alter_order_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.PositiveIntegerField(max_length=12, verbose_name='Phone Number'),
        ),
    ]
