# Generated by Django 4.2 on 2024-02-04 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_alter_order_order_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.PositiveIntegerField(max_length=20, verbose_name='Phone Number'),
        ),
    ]
