# Generated by Django 4.2 on 2024-01-18 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_image',
            field=models.ImageField(default=1, upload_to='user_image/'),
            preserve_default=False,
        ),
    ]
